# Makefile para automatizar tareas

run:
	python main.py "Crea un guion para un video viral de finanzas."

clean:
	del /Q guion.txt imagen_generada.png audio_generado.mp3 subtitulos.srt video_final.mp4
